import type { SubtitleItem, SubtitleStyle } from "../../../lib/types";

let idCounter = 0;
function nextId(): string {
  return `sub-${Date.now().toString(36)}-${++idCounter}`;
}

export function parseSRT(srt: string): SubtitleItem[] {
  if (!srt.trim()) return [];

  const blocks = srt.trim().replace(/\r\n/g, "\n").split(/\n\n+/);
  const items: SubtitleItem[] = [];

  for (const block of blocks) {
    const lines = block.trim().split("\n");
    if (lines.length < 3) continue;

    const timeLine = lines[1];
    const match = timeLine.match(
      /(\d{2}:\d{2}:\d{2}[.,]\d{3})\s*-->\s*(\d{2}:\d{2}:\d{2}[.,]\d{3})/
    );
    if (!match) continue;

    const text = lines.slice(2).join("\n").trim();
    items.push({
      id: nextId(),
      startTime: parseTime(match[1]),
      endTime: parseTime(match[2]),
      text,
    });
  }

  return items;
}

export function toSRT(items: SubtitleItem[]): string {
  return (
    items
      .map(
        (item, i) =>
          `${i + 1}\n${formatTime(item.startTime)} --> ${formatTime(item.endTime)}\n${item.text}`
      )
      .join("\n\n") + (items.length > 0 ? "\n" : "")
  );
}

function escapeAssText(text: string): string {
  return text
    .replace(/\\/g, "\\\\")
    .replace(/\{/g, "\\{")
    .replace(/\}/g, "\\}");
}

export function toASS(items: SubtitleItem[], style: SubtitleStyle): string {
  const header = `[Script Info]
Title: Generated by editor-tarui
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,PingFang SC,${style.fontSize},&H00${style.fontColor.slice(5)}${style.fontColor.slice(3, 5)}${style.fontColor.slice(1, 3)},&H00${style.outlineColor.slice(5)}${style.outlineColor.slice(3, 5)}${style.outlineColor.slice(1, 3)},&H00000000,${style.bold ? -1 : 0},${style.italic ? -1 : 0},0,0,100,100,0,0,1,${style.outlineWidth},0,${style.alignment},10,10,${style.marginV},1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
`;

  const events = items
    .map((item) => {
      const start = formatAssTime(item.startTime);
      const end = formatAssTime(item.endTime);
      return `Dialogue: 0,${start},${end},Default,,0,0,0,,${escapeAssText(item.text)}`;
    })
    .join("\n");

  return header + events + "\n";
}

function formatAssTime(seconds: number): string {
  const h = Math.floor(seconds / 3600);
  const m = Math.floor((seconds % 3600) / 60);
  const s = seconds % 60;
  const cs = Math.round((s - Math.floor(s)) * 100);
  return `${String(h).padStart(1, "0")}:${String(m).padStart(2, "0")}:${String(Math.floor(s)).padStart(2, "0")}.${String(cs).padStart(2, "0")}`;
}

export function formatTime(seconds: number): string {
  const h = Math.floor(seconds / 3600);
  const m = Math.floor((seconds % 3600) / 60);
  const s = seconds % 60;
  const ms = Math.round((s - Math.floor(s)) * 1000);
  return `${String(h).padStart(2, "0")}:${String(m).padStart(2, "0")}:${String(Math.floor(s)).padStart(2, "0")},${String(ms).padStart(3, "0")}`;
}

export function parseTime(time: string): number {
  const match = time.match(/(\d{2}):(\d{2}):(\d{2})[.,](\d{3})/);
  if (!match) return 0;
  return (
    parseInt(match[1]) * 3600 +
    parseInt(match[2]) * 60 +
    parseInt(match[3]) +
    parseInt(match[4]) / 1000
  );
}
